name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: |
          pnpm build:ui
          pnpm build:vue
          pnpm build:react
          
      - name: List build output
        run: |
          echo "Checking build output in root:"
          ls -la $GITHUB_WORKSPACE
          echo "Checking Vue app dist:"
          ls -la $GITHUB_WORKSPACE/apps/vue-app/dist/
          echo "Checking React app dist:"
          ls -la $GITHUB_WORKSPACE/apps/react-app/dist/
          
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 创建临时目录
          mkdir -p $GITHUB_WORKSPACE/temp/vue-app $GITHUB_WORKSPACE/temp/react-app
          
          # 复制构建文件到临时目录
          cp -r  $GITHUB_WORKSPACE/apps/vue-app/dist/*  $GITHUB_WORKSPACE/temp/vue-app/ || echo "No Vue build files"
          cp -r  $GITHUB_WORKSPACE/apps/react-app/dist/*  $GITHUB_WORKSPACE/temp/react-app/ || echo "No React build files"
          
          # 创建导航页
          cat > $GITHUB_WORKSPACE/temp/index.html <<EOL
          <!DOCTYPE html>
          <html>
          <head>
            <title>Frontend Monorepo Demo</title>
            <style>
              body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; }
              h1 { color: #333; }
              .links { margin-top: 20px; }
              .links a { display: inline-block; margin: 10px; padding: 10px 20px; background: #007bff; color: white; text-decoration: none; border-radius: 5px; }
              .links a:hover { background: #0056b3; }
            </style>
          </head>
          <body>
            <h1>Frontend Monorepo Demo</h1>
            <div class="links">
              <a href="./vue-app/">Vue App</a>
              <a href="./react-app/">React App</a>
            </div>
          </body>
          </html>
          EOL
          
          # 切换到 gh-pages 分支
          git checkout --orphan gh-pages
          git reset --hard
          
          # 清理工作目录并移动构建文件
          rm -rf ./*
          mv  $GITHUB_WORKSPACE/temp/vue-app
          mv  $GITHUB_WORKSPACE/temp/react-app
          rm -rf $GITHUB_WORKSPACE/temp
          
          # 添加 .nojekyll 文件以禁用 GitHub Pages Jekyll 处理
          touch .nojekyll
          
          # 提交并推送
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git gh-pages

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: $GITHUB_WORKSPACE/dist/