name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: |
          git clone https://github.com/${{ github.repository }}.git .
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Setup Node.js and PNPM
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          sudo npm install -g pnpm@8
          
      - name: Install dependencies
        run: |
          pnpm install
          
      - name: Build
        run: |
          pnpm build:ui
          pnpm build:vue
          pnpm build:react
          
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 准备部署目录
          mkdir -p dist
          cp -r apps/vue-app/dist/* dist/vue-app/
          cp -r apps/react-app/dist/* dist/react-app/
          
          # 创建导航页
          cat > dist/index.html <<EOL
          <!DOCTYPE html>
          <html>
          <head>
            <title>Frontend Monorepo Demo</title>
            <style>
              body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; }
              h1 { color: #333; }
              .links { margin-top: 20px; }
              .links a { display: inline-block; margin: 10px; padding: 10px 20px; background: #007bff; color: white; text-decoration: none; border-radius: 5px; }
              .links a:hover { background: #0056b3; }
            </style>
          </head>
          <body>
            <h1>Frontend Monorepo Demo</h1>
            <div class="links">
              <a href="./vue-app/">Vue App</a>
              <a href="./react-app/">React App</a>
            </div>
          </body>
          </html>
          EOL
          
          # 切换到 gh-pages 分支
          git checkout --orphan gh-pages
          git reset --hard
          
          # 移动构建文件到根目录
          rm -rf *
          mv dist/* .
          rmdir dist
          
          # 提交并推送
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git gh-pages