name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: |
          git clone https://github.com/${{ github.repository }}.git .
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Setup Node.js and PNPM
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          sudo npm install -g pnpm@8
          
      - name: Install dependencies
        run: |
          pnpm install
          
      - name: Build
        run: |
          pnpm build:ui
          pnpm build:vue
          pnpm build:react
          
      - name: Check build output
        run: |
          echo "Checking Vue build output:"
          ls -la apps/vue-app/dist/
          echo "Checking React build output:"
          ls -la apps/react-app/dist/
          
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 创建临时目录
          mkdir -p temp/vue-app temp/react-app
          
          # 复制构建文件到临时目录
          cp -r apps/vue-app/dist/* temp/vue-app/ || echo "No Vue build files"
          cp -r apps/react-app/dist/* temp/react-app/ || echo "No React build files"
          
          # 调试信息：列出 temp 目录的内容
          echo "Contents of temp directory after copying:"
          ls -la temp/
          
          # 调试信息：列出 vue-app 和 react-app 目录的内容
          echo "Contents of temp/vue-app:"
          ls -la temp/vue-app/
          echo "Contents of temp/react-app:"
          ls -la temp/react-app/
          
          # 创建导航页
          cat > temp/index.html <<EOL
          <!DOCTYPE html>
          <html>
          <head>
            <title>Frontend Monorepo Demo</title>
            <style>
              body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; }
              h1 { color: #333; }
              .links { margin-top: 20px; }
              .links a { display: inline-block; margin: 10px; padding: 10px 20px; background: #007bff; color: white; text-decoration: none; border-radius: 5px; }
              .links a:hover { background: #0056b3; }
            </style>
          </head>
          <body>
            <h1>Frontend Monorepo Demo</h1>
            <div class="links">
              <a href="./vue-app/">Vue App</a>
              <a href="./react-app/">React App</a>
            </div>
          </body>
          </html>
          EOL
          
          # 切换到 gh-pages 分支
          git checkout --orphan gh-pages
          git reset --hard
          
          # 清理工作目录并移动构建文件
          rm -rf ./*
          mv temp/vue-app ./
          mv temp/react-app ./
          rm -rf temp
          
          # 添加 .nojekyll 文件以禁用 GitHub Pages Jekyll 处理
          touch .nojekyll
          
          # 提交并推送
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git gh-pages